version: 1.0.0.{build}
skip_tags: true
branches:
  except:
  - next
skip_commits:
  files:
    - '**/*.md'
max_jobs: 15
image:
- Visual Studio 2017
configuration: Release
platform: Any CPU
cache: externals/Els_kom_new
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
before_build:
- ps: ./update-externals.ps1
build:
  project: callbacktest_plugin.sln
  parallel: true
  verbosity: minimal
test: off
artifacts:
- path: bin/$(configuration)/plugins/*.plugin.*
  name: myartifact
before_deploy:
- ps: ./appveyor-deploy.ps1
deploy:
- provider: GitHub
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: '$(APPVEYOR_REPO_COMMIT_MESSAGE) - $(APPVEYOR_REPO_BRANCH)'
  auth_token:
    secure: oHqKZpK6huL4v9LT6ifeFb/MA3vI1NRlN66jP+qbI7DiGhV0ZF3L7xmTeJR+OEFG
#   repository: Elskom/Els_kom_builds
  artifact: myartifact
  prerelease: false
  force_update: true
  on:
    APPVEYOR_REPO_TAG: false
